services:

  reverse-proxy:
    image: traefik
    container_name: st-reverse-proxy-c
    command: --providers.docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../reverse-proxy/traefik-static.yml:/traefik.yml
      - ../reverse-proxy/traefik-dynamic.yml:/etc/traefik/dynamic/traefik-dynamic.yml
      - ../reverse-proxy/cert/selfsigned.crt:/etc/traefik/certs/selfsigned.crt
      - ../reverse-proxy/cert/selfsigned.key:/etc/traefik/certs/selfsigned.key

  postgresql:
    build: ../postgresql
    image: st-postgresql-i
    container_name: st-postgresql-c
    volumes:
      - ../postgresql/volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../postgresql/.env
    restart: unless-stopped

  pg-admin:
    build: ../pg-admin
    image: st-pgadmin-i
    container_name: st-pgadmin-c
    volumes:
      - ../pg-admin/volume:/var/lib/pgadmin
      - ../database-initializer/backup:/var/lib/pgadmin/storage
    env_file:
      - ../pg-admin/.env
    #ports:
    #  - 9001:80
    restart: unless-stopped
    privileged: true
    user: root

  
  database-initializer:
    build: ../database-initializer
    image: st-database-initializer-i
    container_name: st-database-initializer-c
    env_file:
      - ../database-initializer/.env

  bank-api:
    build: ../bank-api
    image: st-bank-api-i
    container_name: st-bank-api-c
    env_file:
      - ../bank-api/.env.prod
    # ports:
    #   - 8001:80
    restart: unless-stopped

  bank-ui:
    build: ../bank-ui
    image: st-bank-ui-i
    container_name: st-bank-ui-c
    env_file:
      - ../bank-ui/.env
    # ports:
    #   - 8002:80
    restart: unless-stopped

  web-api:
    build: ../web-api
    image: st-web-api-i
    container_name: st-web-api-c
    volumes:
      - ../web-api/database:/app/database
    env_file:
      - ../web-api/.env.prod
    # ports:
    #   - 8003:80
    restart: unless-stopped

  web-ui:
    build: ../web-ui
    image: st-web-ui-i
    container_name: st-web-ui-c
    env_file:
      - ../web-ui/.env
    # ports:
    #   - 8004:80
    restart: unless-stopped

  portainer:
    build: ../portainer
    image: st-portainer-i
    container_name: st-portainer-c
    # ports:
    #   - "9002:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../portainer/mount:/data
    restart: unless-stopped

  ############################################################################# test

  test-bank-api:
    build: ../test-bank-api
    image: st-test-bank-api-i
    container_name: st-test-bank-api-c
    env_file:
      - ../test-bank-api/.env.prod
    volumes:
      - ../test-bank-api/mochawesome-report:/app/mochawesome-report
