services:

  postgresql:
    build: ../postgresql
    image: st-postgresql-i
    container_name: st-postgresql-c
    volumes:
      - ../postgresql/volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../postgresql/.env
    restart: unless-stopped

  pg-admin:
    build: ../pg-admin
    image: st-pgadmin-i
    container_name: st-pgadmin-c
    volumes:
      - ../pg-admin/volume:/var/lib/pgadmin
      - ../database-initializer/backup:/var/lib/pgadmin/storage
    env_file:
      - ../pg-admin/.env
    ports:
      - 9001:80
    restart: unless-stopped
  
  database-initializer:
    build: ../database-initializer
    image: st-database-initializer-i
    container_name: st-database-initializer-c
    env_file:
      - ../database-initializer/.env

  bank-api:
    build: ../bank-api
    image: st-bank-api-i
    container_name: st-bank-api-c
    env_file:
      - ../bank-api/.env
    ports:
      - 8081:80
    restart: unless-stopped

  bank-ui:
    build: ../bank-ui
    image: st-bank-ui-i
    container_name: st-bank-ui-c
    env_file:
      - ../bank-ui/.env
    ports:
      - 8082:80
    restart: unless-stopped

  ############################################################################# test

  test-bank-api:
    build: ../test-bank-api
    image: st-test-bank-api-i
    container_name: st-test-bank-api-c
    env_file:
      - ../test-bank-api/.env
    volumes:
      - ../test-bank-api/mochawesome-report:/app/mochawesome-report